server:
  port: 8082
  servlet:
    context-path: /auth
spring:
  application:
    name: auth
  redis:
    host: 172.16.17.103
    port: 6379
    password: rspwd.Crit
    database: 0
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 10000
        min-idle: 0
    timeout: 10000

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://172.16.17.16:9871/eureka
    registry-fetch-interval-seconds: 5
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    ip-address: 192.168.105.12
#    prefer-ip-address: true
#    status-page-url-path: /auth/info
#    home-page-url-path: /auth/home
#    health-check-url-path: /auth/health
application:
  description: 认证服务
