spring :
  #data source config
  application:
    name: security
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource :
    driver : com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.17.27:3306/crec_dmp_db?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username : zl_db
    password : liuzeminyun@2021
    initsize : 10
    maxActive : 20
    minIdle : 10
    maxWait : 120000
    poolPreparedStatements : false
    maxOpenPreparedStatements : -1
    validationQuery : select 1
    testOnborrow : true
    testOnReturn : true
    testWhileIdle : true
    timeBetweenEvictionRunsMillis : 120000
    filters : log4j,stat
  redis:
    host: 172.16.17.103
    port: 6379
    password: rspwd.Crit
    database: 0
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 10000
        min-idle: 0
    timeout: 10000
#mybatis config
mybatis :
  mapperLocations: classpath:com/liuzemin/server/framework/**/dao/*Dao.xml
session :
  domain : liuzemin.crec
  expire : 1800

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://172.16.17.16:9871/eureka
    registry-fetch-interval-seconds: 5

#hystrix超时
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
#feign配置
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 20000
        loggerLevel: basic

server:
  servlet:
    context-path: /
  port: 8083

application:
  description: 用户，权限，登录

user:
  register:
    roleId: 1003
    programId: 1002
    demanderRoleId: 7
  origin:
    password: 111111
jpush:
  appKey: 93d4e6e32619a05a21bd1959
  masterSecret: 096c07a0ac4fee0c90a99f5c