spring:
  application:
    name: eureka-server

server:
  port: 9871

eureka:
  instance:
    #hostname: localhost
    prefer-ip-address: true
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://172.16.17.7:${server.port}/eureka/
  server:
    use-read-only-response-cache: false
    eviction-interval-timer-in-ms: 3000