spring:
 application:
   name: eureka-server

server:
  port: 9871

eureka:
  instance:
    prefer-ip-address: true
    #hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
  server:
    use-read-only-response-cache: false
    eviction-interval-timer-in-ms: 3000
